roomservice: use force-sync when adding projects with roomservice
This works around the error
GitError: --force-sync not enabled; cannot overwrite a local work tree
when using roomservice.

Since this should only trigger when the device repos haven't been
checked out yet, we can use force-sync to overwrite any roomservice
device paths in the .repo directory.

Change-Id: Iac54a8a2f2913f82f8ca6497b8785a9d5769640b
Ticket: CYNGNOS-735
Signed-off-by: martinusbe <martinusbe@gmail.com>

Conflicts:
	tools/roomservice.py